### ISSUE TITLE
failing during loading with build 3114

### ISSUE THREAD

**Issue by dogsoldier68** [SublimeText/ColdFusion#175]
reloading plugin ColdFusion-master.cflib
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\admin\AppData\Roaming\Sublime Text 3\Packages\ColdFusion-master\cflib.py", line 2, in <module>
    from urllib import urlopen
ImportError: cannot import name urlopen
reloading plugin ColdFusion-master.cfml
reloading plugin ColdFusion-master.coldfusiontagcompletions
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\admin\AppData\Roaming\Sublime Text 3\Packages\ColdFusion-master\coldfusiontagcompletions.py", line 58, in <module>
    class TagAutoComplete(sublime_plugin.EventListener):
  File "C:\Users\admin\AppData\Roaming\Sublime Text 3\Packages\ColdFusion-master\coldfusiontagcompletions.py", line 59, in TagAutoComplete
    cflib = get_class()()
  File "C:\Users\admin\AppData\Roaming\Sublime Text 3\Packages\ColdFusion-master\coldfusiontagcompletions.py", line 8, in get_class
    kls = "taglib." + SETTINGS.get("dictionary") + ".tags"
TypeError: Can't convert 'NoneType' object to str implicitly
reloading plugin ColdFusion-master.functioncompletions
reloading plugin ColdFusion-master.ondotcompletions
reloading plugin ColdFusion-master.tagoperators
plugins loaded
Package Control: Removed directory for orphaned package ColdFusion-master
Package Control: Skipping automatic upgrade, last run at 2017-04-24 16:02:32, next run at 2017-04-24 17:02:32 or after
unloading plugin ColdFusion-master.cflib
unloading plugin ColdFusion-master.cfml
unloading plugin ColdFusion-master.coldfusiontagcompletions
unloading plugin ColdFusion-master.functioncompletions
unloading plugin ColdFusion-master.ondotcompletions
unloading plugin ColdFusion-master.tagoperators

**Comment by atomi** [comment]
use https://github.com/jcberquist/sublimetext-cfml
